/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_nickthecoder_jame_Audio */

#ifndef _Included_uk_co_nickthecoder_jame_Audio
#define _Included_uk_co_nickthecoder_jame_Audio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_nickthecoder_jame_Audio
 * Method:    audio_open
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_Audio_audio_1open
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class uk_co_nickthecoder_jame_Audio_SampleFormat */

#ifndef _Included_uk_co_nickthecoder_jame_Audio_SampleFormat
#define _Included_uk_co_nickthecoder_jame_Audio_SampleFormat
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
