/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_nickthecoder_jame_Events */

#ifndef _Included_uk_co_nickthecoder_jame_Events
#define _Included_uk_co_nickthecoder_jame_Events
#ifdef __cplusplus
extern "C" {
#endif
#undef uk_co_nickthecoder_jame_Events_DEFAULT_REPEAT_DELAY
#define uk_co_nickthecoder_jame_Events_DEFAULT_REPEAT_DELAY 500L
#undef uk_co_nickthecoder_jame_Events_DEFAULT_REPEAT_INTERVAL
#define uk_co_nickthecoder_jame_Events_DEFAULT_REPEAT_INTERVAL 30L
/*
 * Class:     uk_co_nickthecoder_jame_Events
 * Method:    events_poll
 * Signature: ()Luk/co/nickthecoder/jame/event/Event;
 */
JNIEXPORT jobject JNICALL Java_uk_co_nickthecoder_jame_Events_events_1poll
  (JNIEnv *, jclass);

/*
 * Class:     uk_co_nickthecoder_jame_Events
 * Method:    events_enableUnicode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_uk_co_nickthecoder_jame_Events_events_1enableUnicode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     uk_co_nickthecoder_jame_Events
 * Method:    events_keyboardRepeat
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_uk_co_nickthecoder_jame_Events_events_1keyboardRepeat
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
