/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_nickthecoder_jame_Jame */

#ifndef _Included_uk_co_nickthecoder_jame_Jame
#define _Included_uk_co_nickthecoder_jame_Jame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_nickthecoder_jame_Jame
 * Method:    jame_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_Jame_jame_1init
  (JNIEnv *, jclass);

/*
 * Class:     uk_co_nickthecoder_jame_Jame
 * Method:    jame_initSubsystem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_Jame_jame_1initSubsystem
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_co_nickthecoder_jame_Jame
 * Method:    jame_getError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_co_nickthecoder_jame_Jame_jame_1getError
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class uk_co_nickthecoder_jame_Jame_Subsystem */

#ifndef _Included_uk_co_nickthecoder_jame_Jame_Subsystem
#define _Included_uk_co_nickthecoder_jame_Jame_Subsystem
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
