/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_nickthecoder_jame_TrueTypeFont */

#ifndef _Included_uk_co_nickthecoder_jame_TrueTypeFont
#define _Included_uk_co_nickthecoder_jame_TrueTypeFont
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_nickthecoder_jame_TrueTypeFont
 * Method:    trueTypeFont_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_nickthecoder_jame_TrueTypeFont_trueTypeFont_1init
  (JNIEnv *, jclass);

/*
 * Class:     uk_co_nickthecoder_jame_TrueTypeFont
 * Method:    trueTypeFont_open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_TrueTypeFont_trueTypeFont_1open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     uk_co_nickthecoder_jame_TrueTypeFont
 * Method:    trueTypeFont_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_uk_co_nickthecoder_jame_TrueTypeFont_trueTypeFont_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     uk_co_nickthecoder_jame_TrueTypeFont
 * Method:    trueTypeFont_getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_TrueTypeFont_trueTypeFont_1getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     uk_co_nickthecoder_jame_TrueTypeFont
 * Method:    trueTypeFont_getAscent
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_TrueTypeFont_trueTypeFont_1getAscent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     uk_co_nickthecoder_jame_TrueTypeFont
 * Method:    trueTypeFont_getDescent
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_TrueTypeFont_trueTypeFont_1getDescent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     uk_co_nickthecoder_jame_TrueTypeFont
 * Method:    trueTypeFont_getLineHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_TrueTypeFont_trueTypeFont_1getLineHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     uk_co_nickthecoder_jame_TrueTypeFont
 * Method:    trueTypeFont_sizeText
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_TrueTypeFont_trueTypeFont_1sizeText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     uk_co_nickthecoder_jame_TrueTypeFont
 * Method:    trueTypeFont_renderSolid
 * Signature: (JLuk/co/nickthecoder/jame/Surface;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_TrueTypeFont_trueTypeFont_1renderSolid
  (JNIEnv *, jobject, jlong, jobject, jstring, jint, jint, jint);

/*
 * Class:     uk_co_nickthecoder_jame_TrueTypeFont
 * Method:    trueTypeFont_renderBlended
 * Signature: (JLuk/co/nickthecoder/jame/Surface;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_TrueTypeFont_trueTypeFont_1renderBlended
  (JNIEnv *, jobject, jlong, jobject, jstring, jint, jint, jint);

/*
 * Class:     uk_co_nickthecoder_jame_TrueTypeFont
 * Method:    trueTypeFont_renderShaded
 * Signature: (JLuk/co/nickthecoder/jame/Surface;Ljava/lang/String;IIIIII)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_TrueTypeFont_trueTypeFont_1renderShaded
  (JNIEnv *, jobject, jlong, jobject, jstring, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
