/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_nickthecoder_jame_Video */

#ifndef _Included_uk_co_nickthecoder_jame_Video
#define _Included_uk_co_nickthecoder_jame_Video
#ifdef __cplusplus
extern "C" {
#endif
#undef uk_co_nickthecoder_jame_Video_SWSURFACE
#define uk_co_nickthecoder_jame_Video_SWSURFACE 0L
#undef uk_co_nickthecoder_jame_Video_HWSURFACE
#define uk_co_nickthecoder_jame_Video_HWSURFACE 1L
#undef uk_co_nickthecoder_jame_Video_ASYNCBLIT
#define uk_co_nickthecoder_jame_Video_ASYNCBLIT 4L
#undef uk_co_nickthecoder_jame_Video_ANYFORMAT
#define uk_co_nickthecoder_jame_Video_ANYFORMAT 268435456L
#undef uk_co_nickthecoder_jame_Video_DOUBLEBUF
#define uk_co_nickthecoder_jame_Video_DOUBLEBUF 1073741824L
#undef uk_co_nickthecoder_jame_Video_FULLSCREEN
#define uk_co_nickthecoder_jame_Video_FULLSCREEN -2147483648L
/*
 * Class:     uk_co_nickthecoder_jame_Video
 * Method:    video_setMode
 * Signature: (Luk/co/nickthecoder/jame/Surface;IIII)I
 */
JNIEXPORT jint JNICALL Java_uk_co_nickthecoder_jame_Video_video_1setMode
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     uk_co_nickthecoder_jame_Video
 * Method:    video_setWindowTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_co_nickthecoder_jame_Video_video_1setWindowTitle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uk_co_nickthecoder_jame_Video
 * Method:    video_setWindowIcon
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_co_nickthecoder_jame_Video_video_1setWindowIcon
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uk_co_nickthecoder_jame_Video
 * Method:    video_showMousePointer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_co_nickthecoder_jame_Video_video_1showMousePointer
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
